### PR TITLE
Add re-Planner

### PR DESCRIPTION
**Pull request by PepikVaio**
Hello, can you add my re-Planner to list?
Thank you.

### CODE REVIEW

**Comment by alexindigo** [comment]
Looks like it's not a free resources.
And repo is lacking readme content.

**Comment by PepikVaio** [comment]
Lite version is free.

**Comment by StachuDotNet** [comment]
Is [this](https://github.com/PepikVaio/reMarkable/blob/main/reMarkable_paid/re-Planner/(en)%20re-Planner%202024%20(lite)%20-%20Wajsar%20Josef.pdf) the 'lite version' you're referring to?

In the readme update, you advertise this as a fully-customizable calendar. Where is a free version customizable?

As far as I can see, there are huge watermarks on every single page of the "free" static .pdf version of the calendar - this seems to kinda go against the vibe of the rest of `awesome-remarkable`.

If this were to be merged, it might be additionally useful to be up-front that the text in the calendar isn't in English, as well.

**Comment by PepikVaio** [comment]
The free version is as is.
If someone needs to edit something, they have to contact me and I will edit according to the requirements.
You can edit almost everything: colors, font, text, language, left-handed or right-handed versions, shrink rows, enlarge rows, add columns, delete columns, add rows, delete rows, add sheets, delete sheets, add images, etc...

**Comment by Eeems** [comment]
I don't see a license in the repository, so it's not clear what users are allowed to do with the files.
As for the statement of it being fully customizable, I also don't see it as such in its current form. Users having to contact you to modify it is not a customizable solution.

**Comment by PepikVaio** [comment]
OK, how should I proceed? Where should I enter my license information? And where is the contact information?

I have the contact in the document itself.

**Comment by Eeems** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

As for contact, that's not the issue. The issue is the description provided, it should not be called customizable in the current form. The description should change to something like "Calendar template".

**Comment by PepikVaio** [comment]
Hi, I have updated and improved the readme.md file.
I added the license file.
I added the security file.
Is it already ok like this?

I've indicated that it's a template, right in the readme file, and I've also indicated that it can be used as is or modified by agreement.
I also added information about what can be done with the work.

Is there anything else I should do?

I also created a separate repo.
So I am sending a new link:
https://github.com/PepikVaio/reMarkable_re-Planner

**Comment by Eeems** [comment]
> Hi, I have updated and improved the readme.md file. I added the license file. I added the security file. Is it already ok like this?

Yes this is fine.

> 
> I've indicated that it's a template, right in the readme file, and I've also indicated that it can be used as is or modified by agreement. I also added information about what can be done with the work.
> 
> Is there anything else I should do?

The description still says that it can be customized, but in the current free form it cannot. Changing the wording to something similar to `You can pay for a customized version` would better represent what this is.

As for your repo itself, the `.github/PAYMENT.md` seems to be hidden behind some badges on the license page, which is not easy to discover for the user. I would recommend making a section in the readme that has a quick snippet that what is included in the readme is just a simple watermarked version, and that the full version can be purchased, and then link to the payments page.

> 
> I also created a separate repo. So I am sending a new link: https://github.com/PepikVaio/reMarkable_re-Planner

The link in this PR currently 404s and will need to be updated to the new link.

**Comment by PepikVaio** [comment]
> The description still says that it can be customized, but in the current free form it cannot. Changing the wording to something similar to `You can pay for a customized version` would better represent what this is.

modified

> As for your repo itself, the `.github/PAYMENT.md` seems to be hidden behind some badges on the license page, which is not easy to discover for the user. I would recommend making a section in the readme that has a quick snippet that what is included in the readme is just a simple watermarked version, and that the full version can be purchased, and then link to the payments page.

modified

> > I also created a separate repo. So I am sending a new link: https://github.com/PepikVaio/reMarkable_re-Planner
> 
> The link in this PR currently 404s and will need to be updated to the new link.

updated

Thank you

**Comment by PepikVaio** [comment]
Thank you so much.

**Pull request merged**
