### PR TITLE
Added kinde2pdf

### PR DESCRIPTION
**Pull request by teticio**
Hi

Thanks for the awesome repo. I added a link to a tool I made called `kindle2pdf` which I use to be able to read Kindle books on my reMarkable. I hope you consider including it. Thanks!

### CODE REVIEW

**Comment by Eeems** [comment]
The linked repository does not contain a license, so it's not clear what rights have been granted to the user. It also doesn't appear to be a project that is specific to the reMarkable.

**Comment by teticio** [comment]
I added the LICENSE. You are right that it isn't specific to reMarkable, but then it doesn't need to be as all it is doing is converting from Kindle to PDF. So up to you if you want to include it or not, but I think it is useful for people who want to read Kindle books on their reMarkable as I don't think there is any other way to do it right now. Either way, thanks for the consideration.

**Comment by Eeems** [comment]
Most people use calibre for converting kindle books right now, which is also not a rM specific item, and not listed here.

Since this list is meant for projects specific to the rM, and not just something that may be useful to someone using a rM, I'm leaning towards not including it.

**Comment by teticio** [comment]
Whatever you think, I'm easy. Using calibre isn't as easy as it used to be with the new Kindles and, in any case, requires a Kindle device (so you might as well read the books on that) unless you manage to download some old version of the Kindle app.

**Comment by teticio** [comment]
Hi @Eeems . Just in case this sways you in favour of merging: I added a script `pdf2remarkable` which uploads the PDF to the reMarkable Cloud. It can be used stand-alone and is very useful on Linux, for which the official desktop app isn't available. There are other Cloud syncing tools and APIs in your list, but I didn't see any quite so simple as just uploading a PDF from a file.

If it's still a "no", then feel free to close this. Thanks for your consideration!

**Comment by teticio** [comment]
I hadn't tried to connect via USB / SSH before - the guides I saw before looked like they were referring to old versions and the "YOU MAY BRICK YOUR DEVICE" put me off. But this link is super helpful, sorry for not having spotted it before.

The reMarkable desktop doesn't work under Wine since about a year ago. I keep checking but now they are using Qt 6, I don't think anyone has got it working. Wine is even more susceptable to breakage than using the Cloud API IMO. So for me personally, I actually like just having the ability to type a command and have it synched on my cloud, without having to plug the thing in to the USB port. I would use the Chrome extension, but it doesn't have access to files on my computer - that was my motivation for pulling out the API code to run from the CLI.

I think I may not be alone, so yes, if you wouldn't mind merging it, that'd be great.

**Comment by Eeems** [comment]
> The reMarkable desktop doesn't work under Wine since about a year ago. I keep checking but now they are using Qt 6, I don't think anyone has got it working.

I've seen people saying they have it working in wine/proton/lutris/bottles this year in the community discord.

> So for me personally, I actually like just having the ability to type a command and have it synched on my cloud, without having to plug the thing in to the USB port. I would use the Chrome extension, but it doesn't have access to files on my computer - that was my motivation for pulling out the API code to run from the CLI.

The usb web interface can solve that for you completely, as it'll let the device handle the cloud sync, and you can also find resources on the page for removing the need for a usb connection. You can also follow up with something like tailscale or zerotier for remote access to the device. Although this would require running a custom kernel that has wireguard/tun support.

> I think I may not be alone, so yes, if you wouldn't mind merging it, that'd be great.

Sure

**Pull request merged**
