### PR TITLE
Added a suggestion with a sync tool for Mendeley

### PR DESCRIPTION
**Pull request by anilkyelam**
Added a link to my repo: https://github.com/anilkyelam/mendeley-rMsync

### CODE REVIEW

**Comment by Ameb** [comment]
Could you improve the README of your repo? For example, unless you look at the python script it is not clear that it uses rmapi.

**Comment by anilkyelam** [comment]
Sure, let me work on that.

**Comment by anilkyelam** [comment]
Done, thanks! 

https://github.com/anilkyelam/mendeley-rMsync

**Comment by Ameb** [comment]
Looks good, thank you

**Pull request merged**
