### PR TITLE
Add remarkable keywriter - a distraction free keyboard notes app

### PR DESCRIPTION
**Pull request by dps**
More info on the app can be found at https://blog.singleton.io/posts/distraction-free-writing/

### CODE REVIEW

**Comment by CTXz** [comment]
Cool app! Would you mind changing the entry to `reMarkable keywriter` rather than `reMarkable_keywriter` to keep things a little more consistent?

Thanks!

**Comment by dps** [comment]
I think that's what is is if you merge? I messed up the first time so there
are two changes on that branch but I thought I created the pull request
from head after that was fixed.

If not no prob - can easily redo

**Comment by CTXz** [comment]
Oh, pardon me. I have overlooked that second commit somehow.

**Comment by lwb52** [comment]
Does this work with any USB keyboard?
Or under the newest OS version?

**Pull request merged**
