### PR TITLE
add reCatchable cloud tool

### PR DESCRIPTION
**Pull request by lapwat**

### CODE REVIEW

**Comment by lapwat** [comment]
closes #108

**Comment by Ameb** [comment]
Thanks!

I am afraid that your commit does not satisfy the following [guideline](https://github.com/reHackable/awesome-reMarkable/blob/master/CONTRIBUTING.md):

```
Order your suggestions alphabetically.
```

Please change your commit according to the guidelines and I will gladly merge your PR!

**Comment by lapwat** [comment]
Not sure where to put it since the list I want to add it to (Cloud tools) is not sorted alphabetically.

**Comment by Ameb** [comment]
That was true, but you fixed it hehe. Thank you

**Pull request merged**
