### PR TITLE
Added remarkable-node

### PR DESCRIPTION
**Pull request by kevlened**

### CODE REVIEW

**Comment by CTXz** [comment]
Thanks for the PR! I am afraid that your commit does not satisfy the following [guideline](https://github.com/reHackable/awesome-reMarkable/blob/master/CONTRIBUTING.md):

```
Maintain consistent and correct naming (ex: reMarkable, not remarkable or ReMarkable).
```

Please change your commit according to the guidelines and I will gladly merge your PR!

**Comment by kevlened** [comment]
Hmm. What would you like it changed to? `remarkable-node` is the name of the library and "- ReMarkable Cloud * API" is consistent with the adjacent listings.

**Comment by CTXz** [comment]
Just change the entry to `reMarkable-node`, that'd do it.

**Comment by kevlened** [comment]
I see. New npm libraries can't be capitalized, so the naming here wouldn't match the actual library name. I understand the desire to stay consistent with the branding, but it sacrifices correctness in this case. Are you certain you want the change?

**Comment by CTXz** [comment]
Yes, the entry mustn't strictly equate the name of the repository. There are numerous other entries in this list with an entry that deviates from the actual repo name (ex. libremarkable).

**Comment by kevlened** [comment]
Done 👍

**Comment by Evidlo** [comment]
I agree that enforcing standards in the descriptive text is important, but applying this to the project names is the wrong approach in my opinion.

It's weird seeing my libraries in this list no longer match their repo names or package names on pypi.

**Pull request merged**
