### PR TITLE
add Drawj2d

### PR DESCRIPTION
**Pull request by qwert2003**
Add Drawj2d to the list.

### CODE REVIEW

**Comment by beardhatcode** [comment]
The Drawj2d project creates technical drawings from text. One of the output formats is `rm` for the Remarkable. Unfortunately documentation is lacking on how one can take the output file and import it in to the ReMarkable. I presonaly think that this should be addressed before adding it to the list. Or maybe the link should reffer to a page that more clearly spells out how to upload the files to the remarkable.

**Comment by qwert2003** [comment]
Thanks for the quick review.
There is a short step-by-step example on the [drawj2d blog](https://sourceforge.net/p/drawj2d/blog/2020/12/drawj2d-115-released/#7ccf), that shows how to transfer the output file to the reMarkable device using _rmapi_. The drawj2d list item contains the link to the example in the description (HowTo).
If anybody knows a better way to transfer an "rm" file to the device, please let me know.

**Comment by qwert2003** [comment]
Ok, I have extended the drawj2d software (release 1.2.1). It is now able to generate a zip file (containing the drawing and the metadata files) in the format rMAPI expects. Thus only few steps are required:
1. drawj2d -Trmapi drawing.hcl
2. rmapi
3. put out-drawing.zip

The [wiki page](https://sourceforge.net/p/drawj2d/wiki/reMarkable) is up to date.

In my opinion Drawj2d provides a way to get around a few limitations of the reMarkable notebooks:
- straight lines, circles, etc.
- text with line font (truetype fonts also work but display the outlines without fill)
- insert a pdf page into a notebook

**Comment by Ameb** [comment]
Thank you @qwert2003 for the contribution and guide; and @beardhatcode for the review. Do you think the documentation issue is solved now?
Looks good to me

**Comment by Ameb** [comment]
As no further comments have been made

**Pull request merged**
